version: "3.8"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - securin_net
  web_dashboard:
    build:
      context: ./web_dashboard
      dockerfile: Dockerfile
    container_name: web_dashboard
    # ports:
    #   - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_INFLUX_URL=http://localhost:8086/
      - VITE_INFLUX_TOKEN=rahasia_securin
      - VITE_INFLUX_ORG=securin
      - VITE_INFLUX_BUCKET=tes
      - VITE_INFLUX_BUCsKET=securinbucket

      - VITE_FIREBASE_API_KEY=AIzaSyDyAAfyxMqJM8GcnJ_dzIUzbzwT05fMpzY
      - VITE_FIREBASE_AUTH_DOMAIN=securin-b49ed.firebaseapp.com
      - VITE_FIREBASE_DATABASE_URL=https://securin-b49ed-default-rtdb.asia-southeast1.firebasedatabase.app
      - VITE_FIREBASE_PROJECT_ID=securin-b49ed
      - VITE_FIREBASE_STORAGE_BUCKET=securin-b49ed.firebasestorage.app
      - VITE_FIREBASE_MESSAGING_SENDER_ID=969031985343
      - VITE_FIREBASE_APP_ID=1:969031985343:web:9ab82cac6d4b13aca7be0a
      - VITE_FIREBASE_MEASUREMENT_ID=G-0L879YNB5B
      - VITE_GOOGLE_CLIENT_ID=613762948310-2q7gol8s8o4as751td43i51a97s23oia.apps.googleusercontent.com
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin12345
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin12345
      - DOCKER_INFLUXDB_INIT_ORG=securin
      - DOCKER_INFLUXDB_INIT_BUCKET=securinbucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=rahasia_securin
      - INFLUXDB_HTTP_CORS_ENABLED=true
    volumes:
      - ./influxdb:/var/lib/influxdb2
    networks:
      - securin_net

networks:
  securin_net:
    driver: bridge
    name: securin_net

volumes:
  caddy_data:
  caddy_config: